[package]
name = "rusty-paste"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server/bin/main.rs"

[[bin]]
name = "client"
path = "src/client/bin/main.rs"

[dependencies]
tiny_http = "0.12.0"
